language: node_js
sudo: false
node_js:
  - 4
  - 6
  - 7

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint && npm run build && npm test && npm run cover

after_success:
  - cat ./coverage/coverage-final.json | ./node_modules/codecov.io/bin/codecov.io.js
